name: my_flutter_app
description: "A Flight Booking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  razorpay_flutter: ^1.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logofly.png"

flutter:
  uses-material-design: true

  assets:
    - assets/goa.jpg
    - assets/yokohama.jpeg
    - assets/australka.jpg
    - assets/goflybg.jpg
    - assets/aviao.gif
    - assets/purple clouds.jpg
    - assets/logofly.jpg
    - assets/logofly2.png
    - assets/gpay.jpg
    - assets/qr.jpg

