// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-n17J9wbtKW5mHaUYhJzsWYqsubyMWw',
    appId: '1:1023748480701:web:22cb0f3226f5f7b60de1d4',
    messagingSenderId: '1023748480701',
    projectId: 'gofly-baf6f',
    authDomain: 'gofly-baf6f.firebaseapp.com',
    storageBucket: 'gofly-baf6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVboiyWUVxTc0D8dDGOFBH2T95F6wf3F0',
    appId: '1:1023748480701:android:3865e395366483440de1d4',
    messagingSenderId: '1023748480701',
    projectId: 'gofly-baf6f',
    storageBucket: 'gofly-baf6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYn7CvQVlVHCkZ1Le0ykKGt1dcuNRV_R8',
    appId: '1:1023748480701:ios:32ad1330b52eda2d0de1d4',
    messagingSenderId: '1023748480701',
    projectId: 'gofly-baf6f',
    storageBucket: 'gofly-baf6f.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYn7CvQVlVHCkZ1Le0ykKGt1dcuNRV_R8',
    appId: '1:1023748480701:ios:32ad1330b52eda2d0de1d4',
    messagingSenderId: '1023748480701',
    projectId: 'gofly-baf6f',
    storageBucket: 'gofly-baf6f.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-n17J9wbtKW5mHaUYhJzsWYqsubyMWw',
    appId: '1:1023748480701:web:d217ebe6b2d045b90de1d4',
    messagingSenderId: '1023748480701',
    projectId: 'gofly-baf6f',
    authDomain: 'gofly-baf6f.firebaseapp.com',
    storageBucket: 'gofly-baf6f.appspot.com',
  );
}
